version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_SESSION_COOKIE_NAME
      - REACT_APP_BASE_URL
    networks:
      - challenge

networks:
  challenge: